#!/bin/sh

text=""
digits=""

for char in $(echo "$USER" | sed 's/[^a-zA-Z]//g'); do
    text="${text}${char}"
done

for char in $(echo "$USER" | sed 's/[^0-9]//g'); do
    digits="${digits}${char}"
done

if [ "$digits" = "1" ]; then
    echo "You are already at the lowest level"
else
    su - "$text$(expr "$digits" - 1)"
fi
